# This is a simple workflow 

name: 'GitHub Workflow Demo for run on push'

on: 
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sayHello:
    runs-on: 
    steps: 
    - name: runscript-to-say-hello
      run:  echo "Howdy GitHub Actions"
